correctphase: optimize based on integral of real component
JeschkeLab/DeerLab pull request #131
Opened 2021-03-30 07:39 UTC by luisfabib

Closes #114

2021-03-31 18:18 UTC, luisfabib commented
Let's remove the fitting of the imaginary offset.

2021-04-01 16:40 UTC, stestoll requested changes

2021-04-01 16:40 UTC, stestoll commented on deerlab/correctphase.py
>      phase : float scalar, optional
should be string

2021-04-01 16:40 UTC, stestoll commented on test/test_correctphase.py
> +    "Check that the phase correcion works when passing multiple datasets"
fix typo

2021-04-01 17:30 UTC, stestoll approved these changes

2021-04-01 17:32 UTC, merged