deerload: Fix bug when loading BES3T files with entries in manipulation history layer
JeschkeLab/DeerLab pull request #164
Opened 2021-04-23 05:55 UTC by luisfabib

This patches a bug in the `deerload` function that happens in certain BES3T Bruker spectrometer files, where there are entries under the `MANIPULATION HISTORY LAYER` section at the end of the descriptor file. 

The function now breaks the keyword parsing of the descriptor file when reaching this section to avoid the error.

2021-04-23 05:55 UTC, luisfabib commented
This will be patched into v0.13.1 as well.

2021-04-23 06:26 UTC, stestoll requested changes
Add deerload tests

2021-04-27 17:53 UTC, stestoll requested changes
Rename data files to indicate `deerload`-relevant features of the files.

2021-04-27 20:42 UTC, stestoll approved these changes

2021-04-27 20:57 UTC, merged